

export const ProfileData = [
  {
    id: 1,
    "name": "Leanne Graham",
    "email": "Sincere@april.biz",
    "phone": "1-770-736-8031 x56442",
    "website": "http://hildegard.org",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": true,
    "isAdmin" : true,
  },
  {
    id: 2,
    "name": "Ervin Howell",
    "email": "Shanna@melissa.tv",
    "phone": "010-692-6593 x09125",
    "website": "http://anastasia.net",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : false,
  },
  {
    id: 3,
    "name": "Clementine Bauch",
    "email": "Nathan@yesenia.net",
    "phone": "1-463-123-4447",
    "website": "http://ramiro.info",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : false,
  },
  {
    id: 4,
    "name": "Patricia Lebsack",
    "email": "Julianne.OConner@kory.org",
    "phone": "493-170-9623 x156",
    "website": "http://kale.biz",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy.jpg",
    "wishlist": false,
    "isAdmin" : true,
  },
  {
    id: 5,
    "name": "Chelsey Dietrich",
    "email": "Lucio_Hettinger@annie.ca",
    "phone": "(254)954-1289",
    "website": "http://demarco.info",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : false,
  },
  {
    id: 6,
    "name": "Mrs. Dennis Schulist",
    "email": "Karley_Dach@jasper.info",
    "phone": "1-477-935-8478 x6430",
    "website": "http://ola.org",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : false,
  },
  {
    id: 7,
    "name": "Kurtis Weissnat",
    "email": "Telly.Hoeger@billy.biz",
    "phone": "210.067.6132",
    "website": "http://elvis.io",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : false,
  },
  {
    id: 8,
    "name": "Nicholas Runolfsdottir V",
    "email": "Sherwood@rosamond.me",
    "phone": "586.493.6943 x140",
    "website": "http://jacynthe.com",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : false,
  },
  {
    id: 9,
    "name": "Glenna Reichert",
    "email": "Chaim_McDermott@dana.io",
    "phone": "(775)976-6794 x41206",
    "website": "http://conrad.com",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : true,
  },
  {
    id: 10,
    "name": "Clementina DuBuque",
    "email": "Rey.Padberg@karina.biz",
    "phone": "024-648-3804",
    "website": "http://ambrose.net",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": false,
    "isAdmin" : true,
  },
  {
    id: 11,
    "name": "Admin",
    "email": "admin@gmail.com",
    "phone": "1-770-736-8031 x56442",
    "website": "http://admin.org",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": true,
    "isAdmin" : true,
  },
  {
    id: 12,
    "name": "User",
    "email": "user@gmail.com",
    "phone": "1-770-736-8031 x56442",
    "website": "http://user.org",
    "profile_pic": "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
    "wishlist": true,
    "isAdmin" : true,
  },
]

